version: '3.8'

services:
  postgresql:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/postgres/data
    networks:
      - server
  
  backend:
    depends_on:
      - postgresql
    build: ./src/backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_PORT:$NODE_PORT
    environment:
      - DB_HOST=postgresql
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    networks:
      - server
      - client

  frontend:
    depends_on:
      - backend
    build: ./src/frontend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $REACT_PORT:$REACT_PORT
    networks:
      - client  

volumes: 
  db:

networks:
  server:
  client: