version: "3.3"

services:
  postgresql:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=2077
      - DB_PASS=postgres
      - DB_NAME=exchange
    ports:
      - 5431:5431
    command: --init-file /app/data/initdb.sql
    volumes:
        - ./init:/docker-entrypoint-initdb.d
    networks:
      - server
  
  backend:
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: DockerfileBackend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3001:3001
    environment:
      - DB_HOST=postgresql
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=exchange
      - DB_PORT=54321
    networks:
      - server
      - client

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: DockerfileFrontend   
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000 
    networks:
      - client  

networks:
  server: 
    driver: bridge
  client: 
    driver: bridge