version: "3.3"

services:
  postgresql:
    image: postgres
    restart: unless-stopped
    environment:
      - DB_PASS:postgres
      - DB_NAME:postgres
    ports:
      - 5432:5432
    command: --init-file /app/data/init.sql
    volumes:
        - ./initdb.sql:/app/data/initdb.sql
    networks:
      - server
  
  backend:
    depends_on:
      - postgresql
    build:
      context: .docker
      dockerfile: DockerfileBackend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3001:3001
    environment:
      - DB_HOST:postgresql
      - DB_USER:postgres
      - DB_PASS:postgres
      - DB_NAME:exchange
      - DB_PORT:54321
    networks:
      - server
      - client

  frontend:
    depends_on:
      - backend
    build:
      context: .docker
      dockerfile: DockerfileFrontend   
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000 
    networks:
      - client  

networks:
  server: 
    driver: bridge
  client: 
    driver: bridge
